on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'exec name'
        # Default value if no value is explicitly provided
        default: 'default execution'
        # Input has to be provided for the workflow to run
        required: false

defaults:
  run:
    working-directory: 
      scheduled_query_alert_automated_deploy

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_CLIENT_ID: ${{secrets.TF_ARM_SUBSCRIPTION_ID}}
      TF_VAR_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      TF_VAR_SUBSCRIPTION_ID: ${{secrets.TF_ARM_SUBSCRIPTION_ID}}
      TF_VAR_TENANT_ID: ${{secrets.TF_ARM_TENANT_ID}}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        env:
          ARM_CLIENT_ID: ${{secrets.TF_ARM_SUBSCRIPTION_ID}}
          ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
          ARM_SUBSCRIPTION_ID: ${{secrets.TF_ARM_SUBSCRIPTION_ID}}
          ARM_TENANT_ID: ${{secrets.TF_ARM_TENANT_ID}}
        run: terraform plan -var="logAnalyticsResourceGroupName=eShop-Alert-Automation" -var=${{ secrets.VAR_LA_RESOURCE_ID }}

      # Hey Nic . . . rerun the rbac stuff with scope Contributer after az login
      # remove the az login deal from the job